import React from "react";
import { useNavigate } from "react-router-dom";
import backgroundImageFile from "../assets/netmetering.jpg";

function NetMetering() {
  const navigate = useNavigate();

  return (
    <div style={styles.container}>
      <button
        style={styles.backButton}
        onClick={() => navigate("/")}
      >
        ← Back to Home
      </button>

      <div style={styles.card}>
        <h1 style={styles.title}>Net Metering</h1>

        <p style={styles.description}>
          Net Metering allows solar system owners to export excess
          electricity generated by their solar panels back to the grid
          and receive credits on their electricity bills. This helps
          maximize savings and improves the return on investment of
          your solar energy system.
        </p>

        <div style={styles.grid}>
          <div style={styles.featureBox}>
            <h3> Energy Export</h3>
            <p>
              Send unused solar energy to the utility grid and earn
              credits.
            </p>
          </div>

          <div style={styles.featureBox}>
            <h3> Bill Savings</h3>
            <p>
              Reduce monthly electricity expenses through energy credits.
            </p>
          </div>

          <div style={styles.featureBox}>
            <h3> Green Energy</h3>
            <p>
              Promote clean and sustainable energy usage.
            </p>
          </div>

          <div style={styles.featureBox}>
            <h3>Easy Approval</h3>
            <p>
              Assistance with documentation and utility approvals.
            </p>
          </div>
        </div>

        <div style={styles.processSection}>
          <h2>How Net Metering Works</h2>

          <div style={styles.timeline}>
            <div>1️⃣ Solar Panels Generate Electricity</div>
            <div>2️⃣ Home Uses Required Power</div>
            <div>3️⃣ Extra Energy Sent to Grid</div>
            <div>4️⃣ Utility Provides Credits</div>
            <div>5️⃣ Lower Monthly Electricity Bills</div>
          </div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  container: {
    minHeight: "100vh",
    backgroundImage: `url(${backgroundImageFile})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "30px",
    position: "relative",
  },

  backButton: {
    position: "absolute",
    top: "25px",
    left: "25px",
    padding: "12px 22px",
    border: "none",
    borderRadius: "8px",
    background: "#ff9800",
    color: "#fff",
    cursor: "pointer",
    fontWeight: "bold",
  },

  card: {
    maxWidth: "750px",
    width: "100%",
    background: "rgba(255,255,255,0.15)",
    backdropFilter: "blur(15px)",
    borderRadius: "25px",
    padding: "40px",
    color: "#fff",
    border: "1px solid rgba(255,255,255,0.3)",
  },

  title: {
    textAlign: "center",
    fontSize: "3rem",
    marginBottom: "20px",
    color: "#f6ff00",
  },

  description: {
    textAlign: "center",
    color:"black",
    lineHeight: "1.8",
    marginBottom: "35px",
    fontSize: "17px",
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "20px",
  },

  featureBox: {
    background: "rgba(241, 228, 228, 0.12)",
    padding: "20px",
      color:"black",
    borderRadius: "15px",
    textAlign: "center",
  },

  processSection: {
    marginTop: "40px",
      color:"black",
    textAlign: "center",
  },

  timeline: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "15px",
      color:"black",
    marginTop: "20px",
  },
};

export default NetMetering;