import React from "react";
import SolarJourneyDetails from "./SolarJourneyDetails";

import image from "../assets/home6.jpg";

const NetMeteringDetails = () => {
  return (
    <SolarJourneyDetails
      number="06"
      title="NET METERING"
      subtitle="Assistance with the net metering process so your solar system can be properly connected with the applicable electricity network."
      image={image}
      description="For eligible grid-connected solar projects, net metering can allow electricity generated by the system to be accounted for through the applicable electricity connection and metering arrangement."
      overview="The exact process, eligibility and documentation requirements can vary depending on the applicable electricity distribution authority and project type. Our team helps coordinate the required steps and documentation wherever applicable."
      highlights={[
        {
          title: "Process Guidance",
          text: "We explain the applicable net metering process for your project.",
        },
        {
          title: "Documentation Support",
          text: "Assistance is provided with the documents required for the process.",
        },
        {
          title: "Application Coordination",
          text: "We help coordinate applicable application-related activities.",
        },
        {
          title: "System Information",
          text: "Relevant solar system information is organized for the required process.",
        },
        {
          title: "Grid Connection Support",
          text: "We coordinate project requirements related to the applicable connection process.",
        },
        {
          title: "Customer Guidance",
          text: "Our team keeps you informed about the important stages.",
        },
      ]}
      process={[
        {
          title: "Check Requirements",
          text: "Applicable project and connection requirements are reviewed.",
        },
        {
          title: "Prepare Documentation",
          text: "Required project and customer documentation is organized.",
        },
        {
          title: "Submit / Coordinate",
          text: "The applicable process is coordinated with the concerned authority.",
        },
        {
          title: "Metering Completion",
          text: "The project proceeds through the applicable metering and connection stages.",
        },
      ]}
      benefits={[
        "Professional process guidance",
        "Documentation assistance",
        "Better coordination",
        "Clearer understanding of requirements",
        "Reduced administrative confusion",
        "Support throughout the process",
      ]}
    />
  );
};

export default NetMeteringDetails;