import React, { useState } from "react";

export default function ChatBox() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    {
      role: "ai",
      text: "👋 Welcome to AVS Solar Consultancy! How can I help you today?",
    },
  ]);
  const [input, setInput] = useState("");

  const getAVSResponse = (question) => {
    const q = question.toLowerCase();

    if (q.includes("service")) {
      return "AVS Solar Consultancy provides solar consultation, site surveys, custom solar design, installation, net metering assistance, and after-sales support.";
    }

    if (q.includes("installation")) {
      return "Our installation process includes site survey, custom design, quotation approval, professional installation, testing, and net metering.";
    }

    if (q.includes("net metering")) {
      return "Net metering allows you to export excess electricity generated by your solar system back to the grid and receive credits.";
    }

    if (q.includes("contact")) {
      return "You can contact AVS Solar Consultancy through the Contact Us page for inquiries and quotations.";
    }

    if (q.includes("price") || q.includes("cost")) {
      return "Solar installation costs depend on system size, location, and energy requirements. Contact AVS for a personalized quotation.";
    }

    return "I can help with AVS Solar Consultancy services, solar installation, pricing, net metering, and support.";
  };

  const sendMessage = () => {
    if (!input.trim()) return;

    const userMsg = {
      role: "user",
      text: input,
    };

    const aiMsg = {
      role: "ai",
      text: getAVSResponse(input),
    };

    setMessages((prev) => [...prev, userMsg, aiMsg]);
    setInput("");
  };

  return (
    <>
      {/* Chat Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        style={styles.chatButton}
      >
        💬
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div style={styles.chatContainer}>
          <div style={styles.header}>
            AVS AI Assistant
          </div>

          <div style={styles.messages}>
            {messages.map((msg, index) => (
              <div
                key={index}
                style={{
                  ...styles.message,
                  alignSelf:
                    msg.role === "user"
                      ? "flex-end"
                      : "flex-start",
                  background:
                    msg.role === "user"
                      ? "#ff9800"
                      : "#1f2937",
                }}
              >
                {msg.text}
              </div>
            ))}
          </div>

          <div style={styles.inputArea}>
            <input
              type="text"
              placeholder="Ask about AVS Solar..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) =>
                e.key === "Enter" && sendMessage()
              }
              style={styles.input}
            />

            <button
              onClick={sendMessage}
              style={styles.sendBtn}
            >
              Send
            </button>
          </div>
        </div>
      )}
    </>
  );
}

const styles = {
  chatButton: {
    position: "fixed",
    bottom: "25px",
    right: "25px",
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    border: "none",
    background: "#676665",
    color: "#fff",
    fontSize: "28px",
    cursor: "pointer",
    zIndex: 9999,
  },

  chatContainer: {
    position: "fixed",
    bottom: "95px",
    right: "25px",
    width: "340px",
    height: "450px",
    background: "#fff",
    borderRadius: "25px",
    overflow: "hidden",
    boxShadow: "0 10px 25px rgba(0,0,0,0.25)",
    display: "flex",
    flexDirection: "column",
    zIndex: 9999,
  },

  header: {
    background: "#365782",
    color: "#fff",
    padding: "15px",
    textAlign: "center",
    fontWeight: "bold",
  },

  messages: {
    flex: 1,
    padding: "10px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    overflowY: "auto",
  },

  message: {
    padding: "10px",
    borderRadius: "10px",
    color: "#fff",
    maxWidth: "80%",
  },

  inputArea: {
    display: "flex",
    padding: "10px",
    borderTop: "1px solid #e5d8d8",
  },

  input: {
    flex: 1,
    padding: "10px",
    outline: "none",
  },

  sendBtn: {
    marginLeft: "8px",
    padding: "10px 15px",
    background: "#ff9800",
    color: "#fff",
    border: "none",
    cursor: "pointer",
  },
};